using System.Text;
using CardForgeApi.Models;

namespace CardForgeApi.Services;

public class CodeGenerator
{
    public string Generate(CardDefinition card)
    {
        var sb = new StringBuilder();
        var className = ToPascalCase(card.Id);
        var ns = $"CardForge_{className}";

        sb.AppendLine("// Auto-generated by Card Forge");
        sb.AppendLine($"using MegaCrit.Sts2.Core.Modding;");
        sb.AppendLine($"using MegaCrit.Sts2.Core.Models;");
        sb.AppendLine($"using MegaCrit.Sts2.Core.Models.Powers;");
        sb.AppendLine($"using MegaCrit.Sts2.Core.Commands;");
        sb.AppendLine($"using MegaCrit.Sts2.Core.Entities.Creatures;");
        sb.AppendLine($"using MegaCrit.Sts2.Core.Entities.Players;");
        sb.AppendLine($"using MegaCrit.Sts2.Core.Runs;");
        sb.AppendLine($"using MegaCrit.Sts2.Core.Combat;");
        sb.AppendLine($"using HarmonyLib;");
        sb.AppendLine($"using System.Collections.Generic;");
        sb.AppendLine();

        // Mod entry point
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine($"[ModInitializer(\"Initialize\")]");
        sb.AppendLine($"public static class {className}Mod");
        sb.AppendLine("{");
        sb.AppendLine($"    private static Harmony? _harmony;");
        sb.AppendLine();
        sb.AppendLine($"    public static void Initialize()");
        sb.AppendLine($"    {{");
        sb.AppendLine($"        _harmony = new Harmony(\"com.cardforge.{card.Id}\");");
        sb.AppendLine($"        _harmony.PatchAll(typeof({className}Mod).Assembly);");
        sb.AppendLine($"        Log.Warn(\"[{card.Name}] Card Forge mod loaded\");");
        sb.AppendLine($"    }}");
        sb.AppendLine("}");
        sb.AppendLine();

        // Card class
        sb.AppendLine($"public class {className}Card : CardModel");
        sb.AppendLine("{");
        sb.AppendLine($"    public override LocString Title => \"{card.Name}\";");
        sb.AppendLine($"    public override string Id => new ModelId(\"CARD_{card.Id.ToUpper()}\");");
        sb.AppendLine($"    public override CardRarity Rarity => CardRarity.{card.Rarity};");
        sb.AppendLine($"    public override CardType CardType => CardType.{card.Type};");
        sb.AppendLine();

        // Cost
        if (card.UseStarCost)
        {
            sb.AppendLine($"    public override int StarCost => {card.Cost};");
        }
        else
        {
            sb.AppendLine($"    public override int EnergyCost => {card.Cost};");
        }
        sb.AppendLine();

        // Tags
        GenerateTags(sb, card);

        // Play effect
        sb.AppendLine($"    public override void OnPlay(Creature target, Creature source, object? context)");
        sb.AppendLine($"    {{");
        GenerateEffects(sb, card);
        sb.AppendLine($"    }}");
        sb.AppendLine();

        // Upgrades
        GenerateUpgrades(sb, card);

        sb.AppendLine("}");

        return sb.ToString();
    }

    private void GenerateTags(StringBuilder sb, CardDefinition card)
    {
        if (card.Tags.Contains("Exhaust")) sb.AppendLine("    public override bool Exhaust => true;");
        if (card.Tags.Contains("Ethereal")) sb.AppendLine("    public override bool Ethereal => true;");
        if (card.Tags.Contains("Innate")) sb.AppendLine("    public override bool Innate => true;");
        if (card.Tags.Contains("Retain")) sb.AppendLine("    public override bool Retain => true;");
        if (card.Tags.Contains("Eternal")) sb.AppendLine("    public override bool Eternal => true;");
        if (card.Tags.Contains("Sly")) sb.AppendLine("    public override bool Sly => true; // 奇巧：弃掉时免费打出");
        if (card.Tags.Contains("Replay")) sb.AppendLine("    public override bool Replay => true; // 重放：额外打出一次");
        if (card.Tags.Contains("Unplayable")) sb.AppendLine("    public override bool Unplayable => true;");
        if (card.Tags.Count > 0) sb.AppendLine();
    }

    private void GenerateEffects(StringBuilder sb, CardDefinition card)
    {
        foreach (var effect in card.Effects)
        {
            var val = effect.Params.TryGetValue("value", out var je) ? je.GetInt32() : 0;
            switch (effect.Keyword)
            {
                case "damage":
                    sb.AppendLine($"        target.LoseHpInternal({val}, default);");
                    break;
                case "block":
                    sb.AppendLine($"        // Block: handled by game engine based on Dexterity");
                    break;
                case "draw":
                    sb.AppendLine($"        // Draw {val} cards - requires DrawCmd integration");
                    break;
                case "vulnerable":
                    sb.AppendLine($"        PowerCmd.Apply<VulnerablePower>(target, {val}, source, null, false);");
                    break;
                case "weak":
                    sb.AppendLine($"        PowerCmd.Apply<WeakPower>(target, {val}, source, null, false);");
                    break;
                case "frail":
                    sb.AppendLine($"        PowerCmd.Apply<FrailPower>(target, {val}, source, null, false);");
                    break;
                case "poison":
                    sb.AppendLine($"        PowerCmd.Apply<PoisonPower>(target, {val}, source, null, false);");
                    break;
                case "strength":
                    sb.AppendLine($"        PowerCmd.Apply<StrengthPower>(target, {val}, source, null, false);");
                    break;
                case "dexterity":
                    sb.AppendLine($"        PowerCmd.Apply<DexterityPower>(target, {val}, source, null, false);");
                    break;
                case "artifact":
                    sb.AppendLine($"        PowerCmd.Apply<ArtifactPower>(target, {val}, source, null, false);");
                    break;
                case "regen":
                    sb.AppendLine($"        PowerCmd.Apply<RegenPower>(target, {val}, source, null, false);");
                    break;
                case "thorns":
                    sb.AppendLine($"        PowerCmd.Apply<ThornsPower>(target, {val}, source, null, false);");
                    break;
                case "heal":
                    sb.AppendLine($"        CreatureCmd.Heal(target, {val}, true);");
                    break;
                case "energyGain":
                    sb.AppendLine($"        source.Player.GainEnergy({val});");
                    break;
                case "energyNextTurn":
                    sb.AppendLine($"        PowerCmd.Apply<EnergyNextTurnPower>(source, {val}, source, null, false);");
                    break;
                case "loseHp":
                    sb.AppendLine($"        source.LoseHpInternal({val}, default);");
                    break;
                case "maxHp":
                    sb.AppendLine($"        target.IncreaseMaxHp({val}, true);");
                    break;
                case "vigor":
                    sb.AppendLine($"        PowerCmd.Apply<VigorPower>(target, {val}, source, null, false);");
                    break;
                case "plating":
                    sb.AppendLine($"        PowerCmd.Apply<PlatingPower>(target, {val}, source, null, false);");
                    break;
                case "intangible":
                    sb.AppendLine($"        PowerCmd.Apply<IntangiblePower>(target, {val}, source, null, false);");
                    break;
                case "buffer":
                    sb.AppendLine($"        PowerCmd.Apply<BufferPower>(target, {val}, source, null, false);");
                    break;
                case "ritual":
                    sb.AppendLine($"        PowerCmd.Apply<RitualPower>(target, {val}, source, null, false);");
                    break;
                case "metallicize":
                    sb.AppendLine($"        PowerCmd.Apply<MetallicizePower>(target, {val}, source, null, false);");
                    break;
                case "focus":
                    sb.AppendLine($"        PowerCmd.Apply<FocusPower>(target, {val}, source, null, false);");
                    break;
                case "channelLightning":
                    sb.AppendLine($"        // Channel Lightning Orb");
                    break;
                case "channelFrost":
                    sb.AppendLine($"        // Channel Frost Orb");
                    break;
                case "channelDark":
                    sb.AppendLine($"        // Channel Dark Orb");
                    break;
                case "channelPlasma":
                    sb.AppendLine($"        // Channel Plasma Orb");
                    break;
                case "channelGlass":
                    sb.AppendLine($"        // Channel Glass Orb");
                    break;
                case "evoke":
                    sb.AppendLine($"        // Evoke rightmost Orb");
                    break;
                case "replay":
                    sb.AppendLine($"        // Replay: card is played additional {val} time(s)");
                    break;
                case "doom":
                    sb.AppendLine($"        PowerCmd.Apply<DoomPower>(target, {val}, source, null, false);");
                    break;
                case "summon":
                    sb.AppendLine($"        // Summon Osty with {val} HP");
                    break;
                case "forge":
                    sb.AppendLine($"        // Forge {val} - Regent mechanic");
                    break;
                default:
                    sb.AppendLine($"        // TODO: implement {effect.Keyword} effect ({val})");
                    break;
            }
        }
    }

    private void GenerateUpgrades(StringBuilder sb, CardDefinition card)
    {
        var upgrade = card.Upgrade;
        if (upgrade.Levels.Count == 0 && upgrade.AutoRule == null) return;

        sb.AppendLine("    public override void ApplyUpgrade(int level)");
        sb.AppendLine("    {");

        if (upgrade.Mode == "auto" && upgrade.AutoRule != null)
        {
            var field = Capitalize(upgrade.AutoRule.Field);
            var delta = upgrade.AutoRule.Value;
            sb.AppendLine($"        base.{field} += {delta} * level;");
        }
        else
        {
            for (int i = 0; i < upgrade.Levels.Count; i++)
            {
                var level = upgrade.Levels[i];
                var condition = i == 0 ? "if" : "else if";
                sb.AppendLine($"        {condition} (level == {i + 1})");
                sb.AppendLine("        {");
                foreach (var change in level.Changes)
                {
                    if (change.Type == "numeric")
                    {
                        var field = Capitalize(change.Field ?? "damage");
                        sb.AppendLine($"            base.{field} += {change.Value};");
                    }
                    else if (change.Type == "keyword")
                    {
                        if (change.Action == "add")
                            sb.AppendLine($"            AddKeyword(CardKeyword.{change.Keyword});");
                        else if (change.Action == "remove")
                            sb.AppendLine($"            RemoveKeyword(CardKeyword.{change.Keyword});");
                    }
                }
                sb.AppendLine("        }");
            }
        }

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static string ToPascalCase(string input)
    {
        var parts = input.Split('_', ' ', '-');
        return string.Concat(parts.Select(p => char.ToUpper(p[0]) + p[1..].ToLower()));
    }

    private static string Capitalize(string s) => char.ToUpper(s[0]) + s[1..].ToLower();
}
